# Generated by Django 3.0.8 on 2020-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(choices=[('A', 'AC ROOMS'), ('N', 'NON-AC ROOMS'), ('D', 'DELUXE ROOMS')], max_length=1)),
                ('availability', models.CharField(choices=[('A', 'AVAILABLE'), ('NA', 'NOT AVAILABLE')], max_length=2)),
                ('guests', models.IntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('book_room', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_prices', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
